### ISSUE TITLE
code gives error please help

### ISSUE THREAD

**Issue by emilhse** [luni64/TeensyLoadcell#1]
Arduino: 1.8.13 (Windows 7), TD: 1.53, Board: "Teensy 3.2 / 3.1, Serial, 72 MHz, Faster, US English"

C:\Users\Emilio\Documents\Arduino\libraries\TeensyLoadcell-master\src\TeensyLoadCell.cpp:4:17: error: operator '==' has no left operand

 #if ADC_USE_PGA == 0

                 ^

C:\Users\Emilio\Documents\Arduino\libraries\TeensyLoadcell-master\src\TeensyLoadCell.cpp: In member function 'void TeensyLoadcell::Loadcell::start()':

C:\Users\Emilio\Documents\Arduino\libraries\TeensyLoadcell-master\src\TeensyLoadCell.cpp:75:29: error: no matching function for call to 'ADC_Module::enableInterrupts()'

       adc->enableInterrupts();

                             ^

In file included from C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\ADC/ADC.h:59:0,

                 from C:\Users\Emilio\Documents\Arduino\libraries\TeensyLoadcell-master\src\TeensyLoadcell.h:3,

                 from C:\Users\Emilio\Documents\Arduino\libraries\TeensyLoadcell-master\src\TeensyLoadCell.cpp:1:

C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\ADC/ADC_Module.h:184:10: note: candidate: void ADC_Module::enableInterrupts(void (*)(), uint8_t)

     void enableInterrupts(void (*isr)(void), uint8_t priority = 255);

          ^

C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\ADC/ADC_Module.h:184:10: note:   candidate expects 2 arguments, 0 provided

Error compiling for board Teensy 3.2 / 3.1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by luni64** [comment]
See
https://forum.pjrc.com/threads/57890-TeensyLoadcell-Direct-Loadcell-Readout-with-T3-2?p=254068&viewfull=1#post254068
